import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { Navbar, NavbarBrand, NavbarCollapse, NavbarLink, NavbarToggle, Footer, FooterBrand, FooterCopyright, FooterDivider, FooterLink, FooterLinkGroup } from "flowbite-react"
import { FaInstagram, FaLine } from "react-icons/fa"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar fluid rounded className="sticky top-0 z-50">
          <NavbarBrand as={Link} href="/">
            <img
              src="https://flowbite.com/docs/images/logo.svg"
              className="mr-3 h-6 sm:h-9"
              alt="Flowbite React Logo"
            />
            <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
              Flowbite React
            </span>
          </NavbarBrand>
          <NavbarToggle />
          <NavbarCollapse>
            <NavbarLink href="projects">企画</NavbarLink>
            <NavbarLink href="info">案内</NavbarLink>
            <NavbarLink href="timetable">スケジュール</NavbarLink>
            <NavbarLink href="map">マップ</NavbarLink>
          </NavbarCollapse>
        </Navbar>

        {children}

        <Footer container>
          <div className="w-full text-center">
            <div className="w-full justify-between sm:flex sm:items-center sm:justify-between">
              <FooterBrand
                href="/"
                src="https://flowbite.com/docs/images/logo.svg"
                alt="Flowbite Logo"
                name="Flowbite"
              />

              <div className="flex mt-4 sm:mt-0 sm:ml-6 gap-4">
                <a
                  href="#"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-500 hover:text-pink-600 text-2xl"
                >
                  <FaInstagram />
                </a>
                <a
                  href="#"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-500 hover:text-green-500 text-2xl"
                >
                  <FaLine />
                </a>
              </div>
            </div>
            <FooterDivider />
            <FooterCopyright href="#" by="Flowbite™" year={2022} />
          </div>
        </Footer>
      </body>
    </html>
  )
}
